version: 2
executorType: docker
containerInfo:
  - image: scizzorz/rain
stages:
  build:
    workDir: ~/
    steps:
      - type: checkout
        path: ~/rain

      - type: shell
        name: "Install Python dependencies"
        pwd: ~/rain
        command: |
          pip3 install -r requirements.txt

      - type: shell
        name: "Run Python tests"
        pwd: ~/rain
        environment:
          - RAINLIB: ./core
          - RAINBASE: ./base
          - PYTHONPATH: .
        command: |
          tests/fix.sh
          mkdir -p /tmp/results
          py.test -rap -v --tb=long --cov=rain --junit-xml=/tmp/results/py.test.xml

      - type: shell
        name: "Run Rain tests"
        pwd: ~/rain
        environment:
          - RAINLIB: ./core
          - RAINBASE: ./base
          - PYTHONPATH: .
        command: |
          ./python -m rain tests
          ./tests.out

      - type: shell
        name: "Run linter"
        pwd: ~/rain
        environment:
          - RAINLIB: ./core
          - RAINBASE: ./base
          - PYTHONPATH: .
        command: |
          ./flake

      - type: test-results-store
        path: /tmp/results

#- cd tests/lib && make init suite && LD_LIBRARY_PATH=./criterion/build ./suite --xml=$CIRCLE_TEST_REPORTS/tests_c.xml
